<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">Main</li>

                <li>
                    <a href="./" class="lazy waves-effect">
                        <i class="ri-dashboard-line"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="./profile" class="lazy waves-effect">
                        <i class="ri-user-3-line"></i>
                        <span>Profile</span>
                    </a>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="ri-send-plane-line"></i>
                        <span>Funds Transfer</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li>
                            <a href="./transfer/local" class="lazy">Local Banks</a>
                        </li>
                        <li>
                            <a href="./transfer/same" class="lazy">Same Bank</a>
                        </li>
                        <li>
                            <a href="./transfer/intl" class="lazy">Wire / Intl</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="./statement" class="lazy waves-effect">
                        <i class="ri-bar-chart-line"></i>
                        <span>E-Statement</span>
                    </a>
                </li>

                <li>
                    <a href="./support" class="waves-effect lazy">
                        <i class="ri-customer-service-2-fill"></i>
                        <span>Get Help</span>
                    </a>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="ri-percent-line"></i>
                        <span>Loans</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li>
                            <a href="./loans/apply" class="lazy">Apply for loan</a>
                        </li>
                        <li>
                            <a href="./loans" class="lazy">Loan History</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="./deposit" class="lazy waves-effect">
                        <i class="ri-wallet-3-line"></i>
                        <span>Deposit</span>
                    </a>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="ri-bank-card-line"></i>
                        <span>Bank Cards</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li>
                            <a href="./bank_cards/request" class="lazy">Request for card</a>
                        </li>
                        <li>
                            <a href="./bank_cards" class="lazy">Approved Cards</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="./logout" class="lazy waves-effect">
                        <i class="ri-logout-circle-r-line"></i>
                        <span>Logout</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="main-content">
